# Generated by Django 4.2.5 on 2024-03-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='../utils/black.jpg', null=True, upload_to='merchants/profiles/')),
                ('merchant_zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchants/merchant_logos/')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('shipping_options', models.CharField(blank=True, choices=[('standard', 'Standard'), ('express', 'Express')], max_length=100, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Merchant Profile',
                'verbose_name_plural': 'Merchant Profiles',
                'db_table': 'merchants_profiles',
            },
        ),
    ]
