# Generated by Django 4.2.5 on 2024-03-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/merchant/profiles/')),
                ('address', models.TextField(blank=True, null=True)),
                ('merchant_zip_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Merchant Profile',
                'verbose_name_plural': 'Merchant Profiles',
                'db_table': 'merchants_profiles',
            },
        ),
    ]
