# Generated by Django 4.2.5 on 2024-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='merchants/profiles/'),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
