# Generated by Django 4.2.5 on 2024-03-11 19:27

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import reviews.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_remove_productreview_customer_and_more'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rating', models.IntegerField(validators=[reviews.validators.validate_rating])),
                ('review', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'db_table': 'product_reviews',
                'ordering': ['-created'],
                'unique_together': {('product', 'customer')},
            },
        ),
    ]
