# Generated by Django 4.2.5 on 2024-03-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_color_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductReport',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
