# Generated by Django 4.2.5 on 2024-05-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/customers/profiles/'),
        ),
    ]
