# Generated by Django 4.2.5 on 2024-05-20 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField(blank=True, null=True)),
                ('payment_information', models.TextField(blank=True, null=True)),
                ('terms_agreement', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'merchants',
            },
            bases=('customers.merchantbridge',),
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='merchants/profiles/')),
                ('merchant_zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchants/merchant_logos/')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('shipping_options', models.CharField(blank=True, choices=[('standard', 'Standard'), ('express', 'Express')], max_length=100, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Profile',
                'verbose_name_plural': 'Merchant Profiles',
                'db_table': 'merchants_profiles',
            },
        ),
    ]
