# Generated by Django 4.2.5 on 2024-05-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cart_product_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
