# Generated by Django 4.2.5 on 2024-05-18 01:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=255, null=True, unique=True),
        ),
    ]
