# Generated by Django 4.2.5 on 2024-05-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=400, null=True, upload_to='images/products/'),
        ),
    ]
